
spring:

  security:
#    user:
#      name: admin
#      password: admin

  jackson:
    mapper:
      accept_case_insensitive_properties: true
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:exam
    username: sa
    password: pass
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

